### PR TITLE
Configure adaptors

### PR DESCRIPTION
**Pull request by 0x006EA1E5**
Configure adaptors with ApplicationContext, BeanFactory etc

### CODE REVIEW

**Comment by 0x006EA1E5** [comment]
What do you guys think of this?

It seems reasonable to configure the adaptors with the properties they would have if instantiated as `@Bean`s, if the values are non-null 

`KinesisMessageDrivenChannelAdapter` especially actually uses the `ApplicationEventPublisher` to publish `KinesisShardEndedEvent`s.

Without this, the `ApplicationEventPublisher` needs adding via a `ConsumerEndpointCustomizer<KinesisMessageDrivenChannelAdapter>` `@Bean`.

**Review by artembilan — CHANGES_REQUESTED** [review]
I think this are so common options that they have to be applied from the core level in the `AbstractMessageChannelBinder`.

Please, consider to raise similar PR in the Spring Cloud Stream project instead.

Also: we don't use `this.` for method call.
Also: it is better to extract local variable from the method call rather than get a possible inconsistency from two or more calls.

**Comment by 0x006EA1E5** [comment]
Opened https://github.com/0x006EA1E5/spring-cloud-stream/pull/1 instead

**Comment by artembilan** [comment]
? 
This is something wrong: you opened PR against your own repo.
You probably need one for the upstream https://github.com/spring-cloud/spring-cloud-stream

**Comment by 0x006EA1E5** [comment]
Oh dear 🤦 
https://github.com/spring-cloud/spring-cloud-stream/pull/2036

**Pull request closed without merging**
